spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: hiep
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  flyway:
    repair: true
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 5557