export enum Permission{
    PRODUCT_MANAGER='PRODUCT_MANAGER',
    MARKETING_MANAGER = 'MARKETING_MANAGER',
    ACCOUNTING_MANAGER= 'ACCOUNTING_MANAGER',
    LANDINGPAGE_MANAGER = 'LANDINGPAGE_MANAGER',
    SYSTEM_MANAGER = 'SYSTEM_MANAGER'
}