INSERT INTO distributor (id, name, slug, created_date, last_modified_date, email, phone)
VALUES
    (1, 'Saigon Books', 'saigon-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@saigonbooks.com', '02812345678'),
    (2, 'Nhà Xuất Bản Trẻ', 'nha-xuat-ban-tre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxbtre.com', '02823466789'),
    (3, 'FAHASA', 'fahasa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@fahasa.com', '02834567890'),
    (4, 'Phương Nam Book', 'phuong-nam-book', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@phuongnambook.com', '02845678901'),
    (5, 'Kim Đồng', 'kim-dong', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@kimdong.com', '02856789012'),
    (6, 'Nhà Xuất Bản Giáo Dục', 'nha-xuat-ban-giao-duc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxbgiaoduc.com', '02867840123'),
    (7, 'Alpha Books', 'alpha-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@alphabooks.com', '02878961234'),
    (8, 'Minh Long Book', 'minh-long-book', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@minhlongbook.com', '02889062345'),
    (9, 'Đinh Tị Books', 'dinh-ti-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@dinhtibooks.com', '02890163456'),
    (10, 'Đông A Books', 'dong-a-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@dongabooks.com', '02801264567'),
    (11, 'Nhà Xuất Bản Lao Động', 'nha-xuat-ban-lao-dong', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxblaodong.com', '02812345670'),
    (12, 'Thái Hà Books', 'thai-ha-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@thaihabooks.com', '02823466781'),
    (13, 'Nhà Xuất Bản Chính Trị Quốc Gia', 'nha-xuat-ban-chinh-tri-quoc-gia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxbctqg.com', '02834567892'),
    (14, 'Hồng Đức Books', 'hong-duc-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@hongducbooks.com', '02845678903'),
    (15, 'Nhà Xuất Bản Tài Chính', 'nha-xuat-ban-tai-chinh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxbtaichinh.com', '02856789014'),
    (16, 'Văn Lang Books', 'van-lang-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@vanlangbooks.com', '02867840125'),
    (17, 'Nhà Xuất Bản Khoa Học và Kỹ Thuật', 'nha-xuat-ban-khoa-hoc-va-ky-thuat', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@nxkhkt.com', '02878961236'),
    (18, 'Quảng Văn Books', 'quang-van-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@quangvanbooks.com', '02889062347'),
    (19, 'Liên Việt Books', 'lien-viet-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@lienvietbooks.com', '02890163458'),
    (20, 'VietNam Books', 'vietnam-books', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'contact@vietnambooks.com', '02801264569');